### ISSUE TITLE
Can't run adb shell

### ISSUE THREAD

**Issue by kvakl-brodakl** [niizam/Genymotion_A11_libhoudini#10]
I strarted emulator, after that opened terminal on linux and executed `adb shell`. Result:
```
adb server version (41) doesn't match this client (39); killing...
ADB server didn't ACK
Full server startup log: /tmp/adb.1000.log
Server had pid: 101438
--- adb starting (pid 101438) ---
adb I 12-22 17:07:38 101438 101438 main.cpp:57] Android Debug Bridge version 1.0.39
adb I 12-22 17:07:38 101438 101438 main.cpp:57] Version 1:8.1.0+r23-5ubuntu2
adb I 12-22 17:07:38 101438 101438 main.cpp:57] Installed as /usr/lib/android-sdk/platform-tools/adb
adb I 12-22 17:07:38 101438 101438 main.cpp:57] 
adb I 12-22 17:07:38 101438 101438 adb_auth_host.cpp:416] adb_auth_init...
adb I 12-22 17:07:38 101438 101438 adb_auth_host.cpp:174] read_key_file '/home/oleh/.android/adbkey'...
adb I 12-22 17:07:38 101438 101438 adb_auth_host.cpp:391] adb_auth_inotify_init...
adb server killed by remote request

* failed to start daemon
error: cannot connect to daemon
```
Maybe I should change something in GenyMotion settings before creating device?
Will appreciate your help...

**Comment by kvakl-brodakl** [comment]
Managed to update files in emulator as shown in README using Terminal Emulator for Android.
But the problem is - for some reason I can't change android version when creating virtual device. If I change anything from default settings - genymotion just shuts down and doesn't install anything. 
So I'm forced to install Android version 12. Maybe you know where I can get libhoudini for Android 12.0?

**Comment by niizam** [comment]
Weird, mine is running fine on Ubuntu 22.04.3
![image](https://github.com/niizam/Genymotion_A11_libhoudini/assets/45286708/569c8240-bf08-41a1-a81a-8efb3f9cce2f)
What linux distro are you using?

**Comment by kvakl-brodakl** [comment]
Linux Mint 20.1
I managed somehow to install Android 9.0 and use standard ARM transition, but it was more like a black magic and shaman rituals XD

**Comment by niizam** [comment]
Apparently you need to update your adb to the latest version.
How? Figure it out yourself.
