### ISSUE TITLE
sh: can't create /system/vendor/build.prop: Read-only file system

### ISSUE THREAD

**Issue by zhoyifan** [niizam/Genymotion_A11_libhoudini#11]
Laptop configs from 'neofetch' command
OS: Ubuntu 22.04.3 LTS x86_64 
Kernel: 6.2.0-39-generic 
CPU: AMD Ryzen 7 4800H with Radeon Graphics (16) @ 2.900GHz
GPU: AMD ATI 05:00.0 Renoir
GPU: NVIDIA 01:00.0 NVIDIA Corporation TU117M

Genymotion Version 3.6.0 | Revision 20231219-22ea4e2c8f.

For the emulated phone, I use the 'Custom Phone', the first option on the list. But I adjusted the RAM to be 4096 MB. 

Get stuck at the 'tee' command in the second step, which reports the only one line as the title shows.(If I need to be '--verbose', simply tell me.) 
My attempt:
:/ #  ls -l /system/build.prop:
-rw------- 1 root root 3987 2023-09-08 14:21 /system/build.prop
:/ #  chmod 622 /system/vendor/build.prop                                       
chmod: chmod '/system/vendor/build.prop' to 100622: Read-only file system

Now I totally have no idea what is going on.

**Comment by niizam** [comment]
Have you tried to run this command before running tee command?
```bash
adb shell
```
```bash
su
```
```bash
mount -o rw,remount /
```
![image](https://github.com/niizam/Genymotion_A11_libhoudini/assets/45286708/76afe431-6731-4264-af16-b96249fe1896)

**Comment by zhoyifan** [comment]
Thank you for your screenshot. It seems that I directly clicked the "copy" button for the commands,
'su
mount -o rw,remount / '

so then second line is actually not executed. Sorry for my bad.
