### ISSUE TITLE
Not resolved on Mac M2 Pro

### ISSUE THREAD

**Issue by TrustDec** [niizam/Genymotion_A11_libhoudini#12]
After completing the 5 installation steps, the emulator stays at "Starting virtual device.."

**Comment by niizam** [comment]
You don't need libhoudini to run ARM64 Android apps in an ARM64 device ☠️
https://github.com/niizam/Genymotion_A11_libhoudini/issues/9#issuecomment-1825651613

**Comment by TrustDec** [comment]
> 你不需要libhoudini在ARM64设备上运行ARM64 Android应用程序☠️ [#9（评论）](https://github.com/niizam/Genymotion_A11_libhoudini/issues/9#issuecomment-1825651613)

So what should be done? How to install apk

An error occured while deploying the file.
This probably means that the app contains ARM native code and your Genymotion device cannot run ARM instructions. You should either build your native code to x86 or install an ARM translation tool in your device.

**Comment by niizam** [comment]
> > 你不需要libhoudini在ARM64设备上运行ARM64 Android应用程序☠️ [#9（评论）](https://github.com/niizam/Genymotion_A11_libhoudini/issues/9#issuecomment-1825651613)
> 
> So what should be done? How to install apk
> 
> An error occured while deploying the file. This probably means that the app contains ARM native code and your Genymotion device cannot run ARM instructions. You should either build your native code to x86 or install an ARM translation tool in your device.

Please kindly submit proper ticket request in [Genymotion Help Center](https://support.genymotion.com/hc/en-us/requests/new), since this repo only provide library for libhoudini.

**Comment by TrustDec** [comment]
> > > 你不需要libhoudini在ARM64设备上运行ARM64 Android应用程序☠️ [#9（评论）](https://github.com/niizam/Genymotion_A11_libhoudini/issues/9#issuecomment-1825651613)
> > 
> > 
> > So what should be done? How to install apk
> > An error occured while deploying the file. This probably means that the app contains ARM native code and your Genymotion device cannot run ARM instructions. You should either build your native code to x86 or install an ARM translation tool in your device.
> 
> Please kindly submit proper ticket request in [Genymotion Help Center](https://support.genymotion.com/hc/en-us/requests/new), since this repo only provide library for libhoudini.

okey thank you
