### ISSUE TITLE
/sdcard/Android/obb can't access and modify after installing

### ISSUE THREAD

**Issue by nerimoe** [niizam/Genymotion_A11_libhoudini#4]
want to play blue archive but it depended on obb folder

`vbox86p:/sdcard/Android # ls
data  media

vbox86p:/sdcard/Android # mkdir obb
mkdir: 'obb': File exists

1|vbox86p:/sdcard/Android # ls
data  media

vbox86p:/sdcard/Android # rm obb -rf
rm: obb: No such file or directory

1|vbox86p:/sdcard/Android # cd obb

vbox86p:/sdcard/Android/obb # ls
ls: .: No such file or directory

1|vbox86p:/sdcard/Android/obb # `

![图片](https://user-images.githubusercontent.com/57009175/229556576-80fc50a6-c29e-424a-8e33-3820515e1976.png)

**Comment by niizam** [comment]
Try to use [FV File Manager](https://play.google.com/store/apps/details?id=com.folderv.file&hl=id&gl=US), since Android 11 have extra protection on Android folder.

Or you can use adb instead:
```
adb shell
mkdir -p /sdcard/Android/obb/com.nexon.bluearchive
adb push filename.obb /sdcard/Android/obb/obb/com.nexon.bluearchive
```

**Comment by nerimoe** [comment]
![图片](https://user-images.githubusercontent.com/57009175/229683455-37f6e7f9-2fdd-4482-96fd-f1a45bf32c1b.png)

**Comment by nerimoe** [comment]
`adb shell
vbox86p:/ # cd sdcard/Android/                                                                                               
vbox86p:/sdcard/Android # 
vbox86p:/sdcard/Android # ls
data  media
vbox86p:/sdcard/Android # cd obb
vbox86p:/sdcard/Android/obb # ls
ls: .: No such file or directory
1|vbox86p:/sdcard/Android/obb # mkdir test
mkdir: 'test': No such file or directory
1|vbox86p:/sdcard/Android/obb # ls
ls: .: No such file or directory
1|vbox86p:/sdcard/Android/obb # exit
`

**Comment by nerimoe** [comment]
Before install:

```
genymotion:/sdcard/Android # ls
data  media  obb
genymotion:/sdcard/Android # cd obb
genymotion:/sdcard/Android/obb # ls
genymotion:/sdcard/Android/obb # mkdir test
genymotion:/sdcard/Android/obb # ls
test
```
![Screenshot from 2023-04-04 12-18-53](https://user-images.githubusercontent.com/57009175/229686753-d19969df-452c-4415-b9cf-39ba82ffa024.png)

**Comment by alexxed** [comment]
Had this issue where I could not install apps that write to obb. logcat showed permission denied writing to the obb folder. Example: botanicula. Mincraft install worked.

I installed then opengapps x86 nano and then it worked (drag and dropped the zip), so the gapps installed by genymotion did not work for some games.

**Comment by a7md8762** [comment]
any news about this issue? I got this problem too, and it's annoying...

**Comment by niizam** [comment]
Please kindly submit proper ticket request in [Genymotion Help Center](https://support.genymotion.com/hc/en-us/requests/new), since this repo only provide library for libhoudini.
