### ISSUE TITLE
Problem with Android 11 Device

### ISSUE THREAD

**Issue by c0d3xxi** [niizam/Genymotion_A11_libhoudini#9]
there is a problem where the device doesn't restart after the code inside /system/build.prop and /system/vendor/build.prop is modified with the given code.  Once the device is turned off it wont turn on again. The android virtual device used for this was the Google Pixel 3 and the host machine is M1 Mac running Mac OS Ventura 13.4.1. Do provide a solution for this please.

**Comment by stephenwang1011** [comment]
always starting

**Comment by niizam** [comment]
I can't be of much help, as I don't have an ARM Mac device to do the troubleshooting on.

**Comment by yarksee** [comment]
same issue~~~~

**Comment by zlocate** [comment]
Works well with Samsung Galaxy S8 device, Android 11, QEMU-virtualization mode
E.g MiXplorer (ARM64 version works well with houdini build from this repo)
![image](https://github.com/niizam/Genymotion_A11_libhoudini/assets/43764701/cfcf5a99-b1f5-4c03-9d95-2f2e46509d47)

**Comment by jmaneyrol69** [comment]
There is no need for ARM translation tools on mac M1/M2: Genymotion already uses native arm8 (arm64) architecture images.

**Comment by niizam** [comment]
> There is no need for ARM translation tools on mac M1/M2: Genymotion already uses native arm8 (arm64) architecture images.

This is the answer
